-- 01_create_tables.sql
-- Snowflake table definitions for ingestion from the current CSV files.

CREATE OR REPLACE TABLE DIM_CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_NAME VARCHAR(255),
    INDUSTRY VARCHAR(100),
    REGION VARCHAR(50),
    COMPANY_SIZE VARCHAR(50),
    SIGNUP_DATE DATE,
    SALES_CHANNEL VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_PRODUCTS (
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_CATEGORY VARCHAR(100),
    PRICING_TIER VARCHAR(50)
);

CREATE OR REPLACE TABLE FACT_REVENUE_MONTHLY (

    REVENUE_MONTH DATE NOT NULL,
    CUSTOMER_ID NUMBER(38,0),
    PRODUCT_LINE VARCHAR(255),
    ARR NUMBER(38,2),
    MRR NUMBER(38,2),
    BOOKINGS NUMBER(38,2),
    EXPANSION_REVENUE NUMBER(38,2),
    CONTRACTION_REVENUE NUMBER(38,2),
    CHURNED_REVENUE NUMBER(38,2),
    NEW_BUSINESS_REVENUE NUMBER(38,2),
    RENEWAL_REVENUE NUMBER(38,2)

);