USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS FINANCE_AI;

USE DATABASE FINANCE_AI;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS WORKFLOWS;
CREATE SCHEMA IF NOT EXISTS REPORTING;

SHOW SCHEMAS IN DATABASE FINANCE_AI;
