USE ROLE ACCOUNTADMIN;
USE DATABASE FINANCE_AI;

CREATE TABLE IF NOT EXISTS WORKFLOWS.AGENT_RUN_HISTORY (
    id INTEGER AUTOINCREMENT,
    agent_name STRING,
    model_name STRING,
    workflow_type STRING,
    prompt STRING,
    response STRING,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

SHOW TABLES IN SCHEMA FINANCE_AI.WORKFLOWS;
